apiVersion: v1
data:
  home-dashboard.json: |-
    {{ `{
      "__inputs": [],
      "__requires": [
        {
          "type": "panel",
          "id": "dashlist",
          "name": "Dashboard list",
          "version": "5.0.0"
        },
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "5.3.0"
        },
        {
          "type": "panel",
          "id": "text",
          "name": "Text",
          "version": "5.0.0"
        }
      ],
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "content": "<div class=\"text-center dashboard-header\">\n  <span>Home Dashboard</span>\n</div>",
          "editable": true,
          "gridPos": {
            "h": 3,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "links": [],
          "mode": "html",
          "style": {},
          "title": "",
          "transparent": true,
          "type": "text"
        },
        {
          "folderId": null,
          "gridPos": {
            "h": 17,
            "w": 12,
            "x": 0,
            "y": 3
          },
          "headings": true,
          "id": 3,
          "limit": null,
          "links": [],
          "query": "",
          "recent": false,
          "search": false,
          "starred": true,
          "tags": [],
          "title": "Starred dashboards",
          "transparent": false,
          "type": "dashlist"
        },
        {
          "folderId": null,
          "gridPos": {
            "h": 17,
            "w": 12,
            "x": 12,
            "y": 3
          },
          "headings": true,
          "id": 4,
          "limit": null,
          "links": [],
          "query": "",
          "recent": false,
          "search": true,
          "starred": false,
          "tags": [],
          "title": "All dashboards",
          "transparent": false,
          "type": "dashlist"
        }
      ],
      "schemaVersion": 16,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "hidden": true,
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ],
        "type": "timepicker"
      },
      "timezone": "browser",
      "title": "Home dashboard",
      "uid": "UcF-Gl2Wk",
      "version": 2
    }` }}
kind: ConfigMap
metadata:
  labels:
    app: grafana
    grafana_dashboard: "1"
  name: prometheus-operator-grafana-dashboards-home
  namespace: monitoring
