apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: ./logging/
    repoURL: 'https://github.com/gelo22/cluster-dev-gelo-test'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

