installCRDs: false

server:
  certificate:
    enabled: true
    domain: "domain.cluster.dev" # passed with terraform
    issuer:
      name: letsencrypt-prod
      kind: ClusterIssuer

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cluster.dev/domain: domain.shalb.net # passed with terraform
    hosts:
      - domain.cluster.dev # passed with terraform
    tls:
      - secretName: argocd-secret
        hosts:
          - domain.cluster.dev # passed with terraform
  config:
    url: https://domain.cluster.dev # passed with terraform
