  nodeExporter:
    serviceMonitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpoint_node_name]
          targetLabel: node


prometheus-operator:
  alertmanager:
    alertmanagerSpec:
      externalUrl: https://alertmanager.NAME-REPO_NAME.cluster.dev


  grafana:
    enabled: true
   #adminUser: admin
   #adminPassword: prom-operator
    grafana.ini:
      server:
        root_url: https://grafana.NAME-REPO_NAME.cluster.dev


  prometheus:
    prometheusSpec:
      externalUrl: https://prometheus.NAME-REPO_NAME.cluster.dev
      externalLabels:
        cluster_name: NAME-REPO_NAME

