# Example on how to install public helm chart using values file from own repository.
# You point the source to own repo with minimal Chart.yaml and values.yaml declaration.
# Public chart version and repo are set through requirements.yaml
# Sample implementation in /kubernetes/chart/wordpress/ folder
# See details on concept in https://github.com/argoproj/argocd-example-apps/tree/master/helm-dependency
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shalb/cluster.dev.git
    targetRevision: HEAD
    path: kubernetes/charts/wordpress
    helm:
      parameters:
      - name: "nginx-ingress.controller.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
        value: wordpress-argo-test.shalb.net
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    validate: true # Validate resources before applying to k8s, defaults to true.
