installCRDs: false

server:
  certificate:
    enabled: true
    domain: "domain.cluster.dev" # passed with terraform
    issuer:
      name: letsencrypt-prod
      kind: ClusterIssuer

  ingress:
    enabled: true
    annotations:
#      cert-manager.io/cluster-issuer: letsencrypt-prod
#      kubernetes.io/ingress.class: nginx
#      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cluster.dev/domain: domain.shalb.net # passed with terraform
    labels: {}
    hosts:
      - domain.cluster.dev # passed with terraform
    paths:
      - /
    tls:
      - secretName: argocd-cert
        hosts:
          - domain.cluster.dev # passed with terraform
  config:
    url: https://domain.cluster.dev # passed with terraform
