on:
  push:
    paths:
      - 'entrypoint.sh'
      - 'bin/**'
      - 'terraform/**'
      - 'kubernetes/apps/**'
      - 'Dockerfile'
      - '.github/workflows/**'
      - '.cluster.dev/**'
      - 'action.yaml'
    branches:
      - master
jobs:
  deploy_cluster_job:
    runs-on: ubuntu-latest
    name: cluster.dev
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Reconcile Clusters
      id: reconcile
      uses: shalb/cluster.dev@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
        SPACES_SECRET_ACCESS_KEY:  ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        CLUSTER_CONFIG_PATH: "./.cluster.dev/"
    - name: Get the Cluster Credentials
      run: echo -e "\n\033[1;32m${{ steps.reconcile.outputs.ssh }}\n\033[1;32m${{ steps.reconcile.outputs.kubeconfig }}\n\033[1;32m${{ steps.reconcile.outputs.argocd }}"
